# =============================================================================
# 01_generate_ddl.R — Trin 1: Generér Postgres-DDL fra Access-skema
# =============================================================================
# Læser access_schema.yaml (Trin 0b output) + statisk verificeret FK/PK-map
# (kilde: access_database_documenter.pdf) og skriver TO DDL-filer:
#   01a_create_tables.sql — kun CREATE TABLE (FK-fri → bulk-load rækkefølge-fri)
#   01b_foreign_keys.sql  — ALTER TABLE ADD FK (påføres EFTER load + orphan-tjek)
#
# Splittet bevidst (Codex adversarial review): aktive FK'er på et samlet skema
# gør bulk-import rækkefølge-afhængig. To-fase-DDL fjerner det problem.
#
# Konservativ 1:1-migration: bevarer tabel-/kolonne-navne (inkl. æ/ø/å) og
# eksakt casing via double-quote-citater. Kun PK-kolonner får NOT NULL.
#
# Kør:  Rscript 01_generate_ddl.R
# =============================================================================

suppressPackageStartupMessages({
  library(yaml)
})

# --- Lille log-helper (ej rå cat) -------------------------------------------
log_msg <- function(...) message(sprintf("[%s] %s", format(Sys.time(), "%H:%M:%S"), paste0(...)))

# --- Stier -------------------------------------------------------------------
cfg <- yaml::read_yaml("config.yml")$default
schema_path  <- cfg$paths$schema_yaml      # access_schema.yaml
out_tables   <- "01a_create_tables.sql"    # kun CREATE TABLE
out_fks      <- "01b_foreign_keys.sql"     # kun ALTER TABLE ADD FK

# Delt sandhedskilde: map_odbc_type(), PK_MAP, FK_MAP
source("migration_metadata.R", encoding = "UTF-8")
pk_map <- PK_MAP
fk_map <- FK_MAP

# --- Identifier-quoting (bevar casing + æ/ø/å) -------------------------------
q <- function(x) sprintf('"%s"', x)

# =============================================================================
# Generér DDL
# =============================================================================
log_msg("Læser skema: ", schema_path)
schema <- yaml::read_yaml(schema_path)
tabeller <- schema$tabeller
log_msg(length(tabeller), " tabeller indlæst")

hdr <- function(title) c(
  "-- =============================================================================",
  sprintf("-- %s", title),
  sprintf("-- Genereret: %s af 01_generate_ddl.R", format(Sys.time(), "%Y-%m-%d %H:%M:%S")),
  sprintf("-- Kilde: %s + access_database_documenter.pdf", schema_path),
  "-- Konservativ 1:1-migration. Quoted identifiers bevarer casing + æ/ø/å.",
  "-- =============================================================================",
  ""
)

tbl_lines <- hdr("01a_create_tables.sql — CREATE TABLE (FK-fri)")

# --- CREATE TABLE pr. tabel --------------------------------------------------
for (tname in names(tabeller)) {
  tbl <- tabeller[[tname]]
  pk  <- pk_map[[tname]]   # NULL hvis junction
  coldefs <- character(0)

  for (kol in tbl$kolonner) {
    cname <- kol$navn
    is_pk <- !is.null(pk) && identical(cname, pk)
    if (is_pk) {
      # Autonumber-PK → IDENTITY BY DEFAULT (tillader eksplicit Id-import i Trin 2)
      coldef <- sprintf("  %s INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", q(cname))
    } else {
      coldef <- sprintf("  %s %s", q(cname), map_odbc_type(kol$type))
    }
    coldefs <- c(coldefs, coldef)
  }

  tbl_lines <- c(tbl_lines,
    sprintf("CREATE TABLE %s (", q(tname)),
    paste(coldefs, collapse = ",\n"),
    ");",
    "")
}

# --- ALTER TABLE ADD FOREIGN KEY (separat fil) -------------------------------
fk_lines <- c(hdr("01b_foreign_keys.sql — FK påføres EFTER data-load + orphan-tjek"),
  "-- Kør denne fil i Trin 2 NÅR alle tabeller er loadet og orphan-tjek bestået.",
  "")

for (fk in fk_map) {
  stmt <- mk_fk_stmt(fk)
  if (isTRUE(fk$enforced)) {
    fk_lines <- c(fk_lines, stmt)
  } else {
    fk_lines <- c(fk_lines,
      "-- IKKE-gennemtvunget i Access (mulige orphan-rækker).",
      "-- Aktivér KUN hvis orphan-tjek i 02_migrate_data.R er rent:",
      paste0("-- ", stmt))
  }
}

# --- Skriv begge filer UTF-8 / LF --------------------------------------------
write_sql <- function(path, lines) {
  con <- file(path, open = "wb", encoding = "UTF-8")
  writeLines(lines, con, sep = "\n")
  close(con)
}
write_sql(out_tables, tbl_lines)
write_sql(out_fks, fk_lines)

n_fk_active <- sum(vapply(fk_map, function(f) isTRUE(f$enforced), logical(1)))
log_msg("Skrevet: ", out_tables, " + ", out_fks)
log_msg(sprintf("  %d CREATE TABLE | %d aktive FK, %d kommenteret",
                length(tabeller), n_fk_active, length(fk_map) - n_fk_active))
log_msg("Færdig. Review DDL før Trin 2 (02_migrate_data.R).")
